name: 'Dependency Check'
description: 'Github action to execute dependency check as part of a github workflow'
Author: 'javixeneize'
branding:
  icon: 'shield'  
  color: 'red'
inputs:
    project:
        required: true
    path:
        required: true  
    format:
        required: true
    others:
        required: false
runs:
    using: 'docker'
    image: 'docker://owasp/dependency-check-action:latest'
    args:

        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format }}'
        - '--out'
        -  '/github/workspace/reports'
        - '--noupdate'
        - '${{ inputs.others }}'